name: CI workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn package
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
         mvn clean verify sonar:sonar \
          -Dsonar.projectKey= train-ticket-reservation \
          -Dsonar.host.url=http://ec2-3-15-145-202.us-east-2.compute.amazonaws.com:9000/ 
         -Dsonar.login=$squ_3eb24339a27cbdd1fe3599a7b2f921a657858a11

