name: ci/cd pipeline to deploy to tomcat

on: 
  push:
    branches: master  #runs pipeline only when pushing to master branch
jobs:
   build-deploy:
     runs-on: ubuntu latest
     
       steps:
           # checkout repo
           - name: checkout code
             uses: actions/checkout@v1
         
           # set-up java
           - name: set-up jdk
             uses: actions/set-up java@v4
             with:
               distributions: 'temurin'
               java-version: '17'
           
           # build with maven(update)
           - name: validate with maven
              run: mvn validate

          - name: plan with maven
             run: mvn plan
          
          - name: test with maven
             run: mvn test

          - name: package with maven
             run: mvn clean package
        

      
          
       
     
      
