name: CI/CD Pipeline to Deploy Tomcat

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Java & Maven Version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -version

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Verify WAR file
        run: ls -lh target/

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk Test
        run: snyk test --all-projects --severity-threshold=high --json-file-output=snyk-report.json || true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Monitor
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=pom.xml

     
