name: ci/cd pipeline to deploy to tomcat

on: 
  push:
    branches: master  #runs pipeline only when pushing to master branch
jobs:
   build-deploy:
     runs-on: ubuntu-latest
     
     steps:
           # checkout repo
           - name: checkout code
             uses: actions/checkout@v3
         
           # set-up java
           - name: set-up jdk
             uses: actions/setup-java@v3
             with:
               distribution: 'temurin'
               java-version: '11'
          
           - name: validate with maven
             run: mvn validate
              
           - name: compile with maven
             run: mvn compile
          
           - name: test with maven
             run: mvn test
             
           # build with maven(update)
           - name: package with maven
             run: mvn clean package
  
           - name: verify WAR file
             run: ls -lh target/
             
           - name: SonarQube Scan
             uses: SonarSource/sonarqube-scan-action@v2
             with:
              projectBaseDir: .
              args: >
               -Dsonar.projectKey=my_project
               -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
               -Dsonar.login=${{ secrets.SONAR_TOKEN }}

          # (Optional) SonarQube Quality Gate
           - name: SonarQube Quality Gate Check
             uses: SonarSource/sonarqube-quality-gate-action@v1
             with:
              sonarToken: ${{ secrets.SONAR_TOKEN }}
      
          
       
     
      
